// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetV1AuthMeData, GetV1AuthMeErrors, GetV1AuthMeResponses, PostV1AuthLoginData, PostV1AuthLoginErrors, PostV1AuthLoginResponses, PostV1AuthRefreshData, PostV1AuthRefreshErrors, PostV1AuthRefreshResponses, PostV1AuthSignupData, PostV1AuthSignupErrors, PostV1AuthSignupResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postV1AuthSignup = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthSignupData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1AuthSignupResponses, PostV1AuthSignupErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/auth/signup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const postV1AuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthLoginData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1AuthLoginResponses, PostV1AuthLoginErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const postV1AuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthRefreshData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1AuthRefreshResponses, PostV1AuthRefreshErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/auth/refresh',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getV1AuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetV1AuthMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1AuthMeResponses, GetV1AuthMeErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/auth/me',
        ...options
    });
};
