// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteV1BudgetsByIdData, DeleteV1BudgetsByIdErrors, DeleteV1BudgetsByIdResponses, GetV1AuthMeData, GetV1AuthMeErrors, GetV1AuthMeResponses, GetV1BudgetsByIdData, GetV1BudgetsByIdErrors, GetV1BudgetsByIdResponses, GetV1BudgetsData, GetV1BudgetsErrors, GetV1BudgetsResponses, PostV1AuthLoginData, PostV1AuthLoginErrors, PostV1AuthLoginResponses, PostV1AuthRefreshData, PostV1AuthRefreshErrors, PostV1AuthRefreshResponses, PostV1AuthSignupData, PostV1AuthSignupErrors, PostV1AuthSignupResponses, PostV1BudgetsData, PostV1BudgetsErrors, PostV1BudgetsResponses, PutV1BudgetsByIdData, PutV1BudgetsByIdErrors, PutV1BudgetsByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const postV1AuthSignup = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthSignupData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1AuthSignupResponses, PostV1AuthSignupErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/auth/signup',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const postV1AuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthLoginData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1AuthLoginResponses, PostV1AuthLoginErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const postV1AuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthRefreshData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1AuthRefreshResponses, PostV1AuthRefreshErrors, ThrowOnError>({
        responseType: 'json',
        url: '/v1/auth/refresh',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getV1AuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetV1AuthMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1AuthMeResponses, GetV1AuthMeErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/auth/me',
        ...options
    });
};

export const getV1Budgets = <ThrowOnError extends boolean = false>(options?: Options<GetV1BudgetsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1BudgetsResponses, GetV1BudgetsErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/budgets',
        ...options
    });
};

export const postV1Budgets = <ThrowOnError extends boolean = false>(options: Options<PostV1BudgetsData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1BudgetsResponses, PostV1BudgetsErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/budgets',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const deleteV1BudgetsById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1BudgetsByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteV1BudgetsByIdResponses, DeleteV1BudgetsByIdErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/budgets/{id}',
        ...options
    });
};

export const getV1BudgetsById = <ThrowOnError extends boolean = false>(options: Options<GetV1BudgetsByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetV1BudgetsByIdResponses, GetV1BudgetsByIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/budgets/{id}',
        ...options
    });
};

export const putV1BudgetsById = <ThrowOnError extends boolean = false>(options: Options<PutV1BudgetsByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutV1BudgetsByIdResponses, PutV1BudgetsByIdErrors, ThrowOnError>({
        responseType: 'json',
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/v1/budgets/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
