// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://host.docker.internal:7165/' | (string & {});
};

export type AuthResponse = {
    accessToken: string;
    refreshToken: string;
    expiresIn: string;
    tokenType?: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type MeResponse = {
    id: string;
    username: string;
    displayName: string;
    email: string;
    role: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type SignupRequest = {
    username: string;
    displayName: string;
    email: string;
    password: string;
};

export type PostV1AuthSignupData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/signup';
};

export type PostV1AuthSignupErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostV1AuthSignupError = PostV1AuthSignupErrors[keyof PostV1AuthSignupErrors];

export type PostV1AuthSignupResponses = {
    /**
     * Created
     */
    201: AuthResponse;
};

export type PostV1AuthSignupResponse = PostV1AuthSignupResponses[keyof PostV1AuthSignupResponses];

export type PostV1AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type PostV1AuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostV1AuthLoginError = PostV1AuthLoginErrors[keyof PostV1AuthLoginErrors];

export type PostV1AuthLoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostV1AuthLoginResponse = PostV1AuthLoginResponses[keyof PostV1AuthLoginResponses];

export type PostV1AuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/refresh';
};

export type PostV1AuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostV1AuthRefreshError = PostV1AuthRefreshErrors[keyof PostV1AuthRefreshErrors];

export type PostV1AuthRefreshResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostV1AuthRefreshResponse = PostV1AuthRefreshResponses[keyof PostV1AuthRefreshResponses];

export type GetV1AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/me';
};

export type GetV1AuthMeErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type GetV1AuthMeError = GetV1AuthMeErrors[keyof GetV1AuthMeErrors];

export type GetV1AuthMeResponses = {
    /**
     * OK
     */
    200: MeResponse;
};

export type GetV1AuthMeResponse = GetV1AuthMeResponses[keyof GetV1AuthMeResponses];
