// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: 'https://host.docker.internal:7165/' | (string & {});
};

export type AuthResponse = {
    accessToken: string;
    refreshToken: string;
    expiresIn: string;
    tokenType?: string;
};

export type BudgetResponse = {
    id: string;
    displayName: string;
    description: string;
    period: string;
    total: number;
    currency: string;
    ownerId: string;
    createdAt: string;
    updatedAt: string;
};

export type CreateBudgetRequest = {
    displayName: string;
    description: string;
    period: string;
    total: number;
    currency: string;
};

export type LoginRequest = {
    username: string;
    password: string;
};

export type MeResponse = {
    id: string;
    username: string;
    displayName: string;
    email: string;
    role: string;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type SignupRequest = {
    username: string;
    displayName: string;
    email: string;
    password: string;
};

export type UpdateBudgetRequest = {
    displayName: string | null;
    description: string | null;
    period: string | null;
    total: number | null;
    currency: string | null;
};

export type PostV1AuthSignupData = {
    body: SignupRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/signup';
};

export type PostV1AuthSignupErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostV1AuthSignupError = PostV1AuthSignupErrors[keyof PostV1AuthSignupErrors];

export type PostV1AuthSignupResponses = {
    /**
     * Created
     */
    201: AuthResponse;
};

export type PostV1AuthSignupResponse = PostV1AuthSignupResponses[keyof PostV1AuthSignupResponses];

export type PostV1AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type PostV1AuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostV1AuthLoginError = PostV1AuthLoginErrors[keyof PostV1AuthLoginErrors];

export type PostV1AuthLoginResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostV1AuthLoginResponse = PostV1AuthLoginResponses[keyof PostV1AuthLoginResponses];

export type PostV1AuthRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/refresh';
};

export type PostV1AuthRefreshErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type PostV1AuthRefreshError = PostV1AuthRefreshErrors[keyof PostV1AuthRefreshErrors];

export type PostV1AuthRefreshResponses = {
    /**
     * OK
     */
    200: AuthResponse;
};

export type PostV1AuthRefreshResponse = PostV1AuthRefreshResponses[keyof PostV1AuthRefreshResponses];

export type GetV1AuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/me';
};

export type GetV1AuthMeErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type GetV1AuthMeError = GetV1AuthMeErrors[keyof GetV1AuthMeErrors];

export type GetV1AuthMeResponses = {
    /**
     * OK
     */
    200: MeResponse;
};

export type GetV1AuthMeResponse = GetV1AuthMeResponses[keyof GetV1AuthMeResponses];

export type GetV1BudgetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/budgets';
};

export type GetV1BudgetsErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type GetV1BudgetsError = GetV1BudgetsErrors[keyof GetV1BudgetsErrors];

export type GetV1BudgetsResponses = {
    /**
     * OK
     */
    200: Array<BudgetResponse>;
};

export type GetV1BudgetsResponse = GetV1BudgetsResponses[keyof GetV1BudgetsResponses];

export type PostV1BudgetsData = {
    body: CreateBudgetRequest;
    path?: never;
    query?: never;
    url: '/v1/budgets';
};

export type PostV1BudgetsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type PostV1BudgetsError = PostV1BudgetsErrors[keyof PostV1BudgetsErrors];

export type PostV1BudgetsResponses = {
    /**
     * Created
     */
    201: BudgetResponse;
};

export type PostV1BudgetsResponse = PostV1BudgetsResponses[keyof PostV1BudgetsResponses];

export type DeleteV1BudgetsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/budgets/{id}';
};

export type DeleteV1BudgetsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteV1BudgetsByIdError = DeleteV1BudgetsByIdErrors[keyof DeleteV1BudgetsByIdErrors];

export type DeleteV1BudgetsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteV1BudgetsByIdResponse = DeleteV1BudgetsByIdResponses[keyof DeleteV1BudgetsByIdResponses];

export type GetV1BudgetsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/budgets/{id}';
};

export type GetV1BudgetsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetV1BudgetsByIdError = GetV1BudgetsByIdErrors[keyof GetV1BudgetsByIdErrors];

export type GetV1BudgetsByIdResponses = {
    /**
     * OK
     */
    200: BudgetResponse;
};

export type GetV1BudgetsByIdResponse = GetV1BudgetsByIdResponses[keyof GetV1BudgetsByIdResponses];

export type PutV1BudgetsByIdData = {
    body: UpdateBudgetRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/v1/budgets/{id}';
};

export type PutV1BudgetsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutV1BudgetsByIdError = PutV1BudgetsByIdErrors[keyof PutV1BudgetsByIdErrors];

export type PutV1BudgetsByIdResponses = {
    /**
     * OK
     */
    200: BudgetResponse;
};

export type PutV1BudgetsByIdResponse = PutV1BudgetsByIdResponses[keyof PutV1BudgetsByIdResponses];
