/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authAuthRouteImport } from './routes/(auth)/_auth'
import { Route as appHomeRouteImport } from './routes/(app)/_home'
import { Route as appHomeIndexRouteImport } from './routes/(app)/_home.index'
import { Route as authAuthAuthSignupRouteImport } from './routes/(auth)/_auth.auth.signup'
import { Route as authAuthAuthLoginRouteImport } from './routes/(auth)/_auth.auth.login'

const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appHomeRoute = appHomeRouteImport.update({
  id: '/(app)/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const appHomeIndexRoute = appHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appHomeRoute,
} as any)
const authAuthAuthSignupRoute = authAuthAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthAuthLoginRoute = authAuthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => authAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appHomeIndexRoute
  '/auth/login': typeof authAuthAuthLoginRoute
  '/auth/signup': typeof authAuthAuthSignupRoute
}
export interface FileRoutesByTo {
  '/': typeof appHomeIndexRoute
  '/auth/login': typeof authAuthAuthLoginRoute
  '/auth/signup': typeof authAuthAuthSignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/_home': typeof appHomeRouteWithChildren
  '/(auth)/_auth': typeof authAuthRouteWithChildren
  '/(app)/_home/': typeof appHomeIndexRoute
  '/(auth)/_auth/auth/login': typeof authAuthAuthLoginRoute
  '/(auth)/_auth/auth/signup': typeof authAuthAuthSignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/login' | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/login' | '/auth/signup'
  id:
    | '__root__'
    | '/(app)/_home'
    | '/(auth)/_auth'
    | '/(app)/_home/'
    | '/(auth)/_auth/auth/login'
    | '/(auth)/_auth/auth/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appHomeRoute: typeof appHomeRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/_auth': {
      id: '/(auth)/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_home': {
      id: '/(app)/_home'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/_home/': {
      id: '/(app)/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appHomeIndexRouteImport
      parentRoute: typeof appHomeRoute
    }
    '/(auth)/_auth/auth/signup': {
      id: '/(auth)/_auth/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthAuthSignupRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/_auth/auth/login': {
      id: '/(auth)/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthAuthLoginRouteImport
      parentRoute: typeof authAuthRoute
    }
  }
}

interface appHomeRouteChildren {
  appHomeIndexRoute: typeof appHomeIndexRoute
}

const appHomeRouteChildren: appHomeRouteChildren = {
  appHomeIndexRoute: appHomeIndexRoute,
}

const appHomeRouteWithChildren =
  appHomeRoute._addFileChildren(appHomeRouteChildren)

interface authAuthRouteChildren {
  authAuthAuthLoginRoute: typeof authAuthAuthLoginRoute
  authAuthAuthSignupRoute: typeof authAuthAuthSignupRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthAuthLoginRoute: authAuthAuthLoginRoute,
  authAuthAuthSignupRoute: authAuthAuthSignupRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appHomeRoute: appHomeRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
