// This file is auto-generated by @hey-api/openapi-ts

import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { getV1AuthMe, type Options, postV1AuthLogin, postV1AuthRefresh, postV1AuthSignup } from '../sdk.gen';
import type { GetV1AuthMeData, GetV1AuthMeError, GetV1AuthMeResponse, PostV1AuthLoginData, PostV1AuthLoginError, PostV1AuthLoginResponse, PostV1AuthRefreshData, PostV1AuthRefreshError, PostV1AuthRefreshResponse, PostV1AuthSignupData, PostV1AuthSignupError, PostV1AuthSignupResponse } from '../types.gen';

export const postV1AuthSignupMutation = (options?: Partial<Options<PostV1AuthSignupData>>): UseMutationOptions<PostV1AuthSignupResponse, AxiosError<PostV1AuthSignupError>, Options<PostV1AuthSignupData>> => {
    const mutationOptions: UseMutationOptions<PostV1AuthSignupResponse, AxiosError<PostV1AuthSignupError>, Options<PostV1AuthSignupData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1AuthSignup({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postV1AuthLoginMutation = (options?: Partial<Options<PostV1AuthLoginData>>): UseMutationOptions<PostV1AuthLoginResponse, AxiosError<PostV1AuthLoginError>, Options<PostV1AuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostV1AuthLoginResponse, AxiosError<PostV1AuthLoginError>, Options<PostV1AuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1AuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const postV1AuthRefreshMutation = (options?: Partial<Options<PostV1AuthRefreshData>>): UseMutationOptions<PostV1AuthRefreshResponse, AxiosError<PostV1AuthRefreshError>, Options<PostV1AuthRefreshData>> => {
    const mutationOptions: UseMutationOptions<PostV1AuthRefreshResponse, AxiosError<PostV1AuthRefreshError>, Options<PostV1AuthRefreshData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1AuthRefresh({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getV1AuthMeQueryKey = (options?: Options<GetV1AuthMeData>) => createQueryKey("getV1AuthMe", options);

export const getV1AuthMeOptions = (options?: Options<GetV1AuthMeData>) => queryOptions<GetV1AuthMeResponse, AxiosError<GetV1AuthMeError>, GetV1AuthMeResponse, ReturnType<typeof getV1AuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getV1AuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getV1AuthMeQueryKey(options)
});
